# Milestone 1 - Exploratory Data Analysis
_Data Exploration and Preprocessing_

In [ ]:
import pandas as pd
import numpy as np
import pathlib
import os

reviews_path = "../data/raw/Video_Games.jsonl"
meta_path = "../data/raw/meta_Video_Games.jsonl"

In [ ]:
rev_use_colums = ["rating", "title", "text", "timestamp", "helpful_vote", "verified_purchase"]

df = pd.read_json(reviews_path, lines=True)
df.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,4,It’s pretty sexual. Not my fav,I’m playing on ps5 and it’s interesting. It’s...,[],B07DJWBYKP,B07DK1H3H5,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2020-12-17 06:33:24.795,0,True
1,5,Good. A bit slow,Nostalgic fun. A bit slow. I hope they don’t...,[],B00ZS80PC2,B07SRWRH5D,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2020-04-16 15:31:54.941,1,False
2,5,... an order for my kids & they have really en...,This was an order for my kids & they have real...,[],B01FEHJYUU,B07MFMFW34,AGXVBIUFLFGMVLATYXHJYL4A5Q7Q,2017-03-30 12:37:11.000,0,True
3,5,Great alt to pro controller,"These work great, They use batteries which is ...",[],B07GXJHRVK,B0BCHWZX95,AFTC6ZR5IKNRDG5JCPVNVMU3XV2Q,2019-12-29 16:40:34.017,0,True
4,5,solid product,I would recommend to anyone looking to add jus...,[],B00HUWA45W,B00HUWA45W,AFTC6ZR5IKNRDG5JCPVNVMU3XV2Q,2015-03-29 01:18:52.000,0,True

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4624615 entries, 0 to 4624614
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   rating             int64
 1   title              str
 2   text               str
 3   images             object
 4   asin               str
 5   parent_asin        str
 6   user_id            str
 7   timestamp          datetime64[ms]
 8   helpful_vote       int64
 9   verified_purchase  bool
dtypes: bool(1), datetime64[ms](1), int64(2), object(1), str(5)
memory usage: 322.0+ MB

In [16]:
df.isna().mean()

rating               0.0
title                0.0
text                 0.0
images               0.0
asin                 0.0
parent_asin          0.0
user_id              0.0
timestamp            0.0
helpful_vote         0.0
verified_purchase    0.0
dtype: float64

In [8]:
df["title"][0]

'It’s pretty sexual. Not my fav'

In [10]:
df["text"][0]

I’m playing on ps5 and it’s interesting.  It’s unique, massive, and has a neat story.  People are freaking out angry about this game.  I don’t think it’s a top 10 game but it’s definitely a good game on ps5 (played at launch).

In [13]:
df_meta = pd.read_json(meta_path, lines=True)
df_meta.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Video Games,Dash 8-300 Professional Add-On,5.0,1,[Features Dash 8-300 and 8-Q300 ('Q' rollout l...,[The Dash 8-300 Professional Add-On lets you p...,None,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aerosoft,"[Video Games, PC, Games]",{'Pricing': 'The strikethrough price is the Li...,B000FH0MHO,NaN,NaN,NaN
1,Video Games,Phantasmagoria: A Puzzle of Flesh,4.1,18,[Windows 95],[],None,[{'thumb': 'https://m.media-amazon.com/images/...,[],Sierra,"[Video Games, PC, Games]","{'Best Sellers Rank': {'Video Games': 137612, ...",B00069EVOG,NaN,NaN,NaN
2,Video Games,NBA 2K17 - Early Tip Off Edition - PlayStation 4,4.3,223,[The #1 rated NBA video game simulation series...,[Following the record-breaking launch of NBA 2...,58.0,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'NBA 2K17 - Kobe: Haters vs Players...,2K,"[Video Games, PlayStation 4, Games]","{'Release date': 'September 16, 2016', 'Best S...",B00Z9TLVK0,NaN,NaN,NaN
3,Video Games,Nintendo Selects: The Legend of Zelda Ocarina ...,4.9,22,[Authentic Nintendo Selects: The Legend of Zel...,[],37.42,[{'thumb': 'https://m.media-amazon.com/images/...,[],Amazon Renewed,"[Video Games, Legacy Systems, Nintendo Systems...","{'Best Sellers Rank': {'Video Games': 51019, '...",B07SZJZV88,NaN,NaN,NaN
4,Video Games,Thrustmaster Elite Fitness Pack for Nintendo Wii,3.0,3,"[Includes (9) Total Accessories, Pedometer, Wi...",[The Thrustmaster Motion Plus Elite Fitness Pa...,None,[{'thumb': 'https://m.media-amazon.com/images/...,[],THRUSTMASTER,"[Video Games, Legacy Systems, Nintendo Systems...","{'Release date': 'November 1, 2009', 'Pricing'...",B002WH4ZJG,NaN,NaN,NaN

In [15]:
df_meta.info()

<class 'pandas.DataFrame'>
RangeIndex: 137269 entries, 0 to 137268
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   main_category    126234 non-null  str
 1   title            137269 non-null  str
 2   average_rating   137269 non-null  float64
 3   rating_number    137269 non-null  int64
 4   features         137269 non-null  object
 5   description      137269 non-null  object
 6   price            62008 non-null   object
 7   images           137269 non-null  object
 8   videos           137269 non-null  object
 9   store            132908 non-null  str
 10  categories       137269 non-null  object
 11  details          137269 non-null  object
 12  parent_asin      137269 non-null  str
 13  bought_together  0 non-null       float64
 14  subtitle         350 non-null     str
 15  author           262 non-null     object
dtypes: float64(2), int64(1), object(8), str(5)
memory usage: 16.8+ MB

In [17]:
df_meta.isna().mean()

main_category      0.080390
title              0.000000
average_rating     0.000000
rating_number      0.000000
features           0.000000
description        0.000000
price              0.548274
images             0.000000
videos             0.000000
store              0.031770
categories         0.000000
details            0.000000
parent_asin        0.000000
bought_together    1.000000
subtitle           0.997450
author             0.998091
dtype: float64