# Milestone 1 - Exploratory Data Analysis

This notebook contains:

- an overview of the dataset (fields, size, example records)
- inspection of sample records
- selection and justification of fields for retrieval

In [1]:
import pandas as pd
import numpy as np
import pathlib
import os

reviews_path = "../data/raw/Video_Games.jsonl"
meta_path = "../data/raw/meta_Video_Games.jsonl"

## Reviews dataset

In [2]:
df = pd.read_json(reviews_path, lines=True)
df.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,4,It’s pretty sexual. Not my fav,I’m playing on ps5 and it’s interesting. It’s...,[],B07DJWBYKP,B07DK1H3H5,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2020-12-17 06:33:24.795,0,True
1,5,Good. A bit slow,Nostalgic fun. A bit slow. I hope they don’t...,[],B00ZS80PC2,B07SRWRH5D,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2020-04-16 15:31:54.941,1,False
2,5,... an order for my kids & they have really en...,This was an order for my kids & they have real...,[],B01FEHJYUU,B07MFMFW34,AGXVBIUFLFGMVLATYXHJYL4A5Q7Q,2017-03-30 12:37:11.000,0,True
3,5,Great alt to pro controller,"These work great, They use batteries which is ...",[],B07GXJHRVK,B0BCHWZX95,AFTC6ZR5IKNRDG5JCPVNVMU3XV2Q,2019-12-29 16:40:34.017,0,True
4,5,solid product,I would recommend to anyone looking to add jus...,[],B00HUWA45W,B00HUWA45W,AFTC6ZR5IKNRDG5JCPVNVMU3XV2Q,2015-03-29 01:18:52.000,0,True

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4624615 entries, 0 to 4624614
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   rating             int64
 1   title              str
 2   text               str
 3   images             object
 4   asin               str
 5   parent_asin        str
 6   user_id            str
 7   timestamp          datetime64[ms]
 8   helpful_vote       int64
 9   verified_purchase  bool
dtypes: bool(1), datetime64[ms](1), int64(2), object(1), str(5)
memory usage: 322.0+ MB

### Sample Records

In [6]:
idx = 0

title = df["title"][idx]
text = df["text"][idx]

print(f"# Title:\n{title}\n# Text:\n{text}")

# Title:
It’s pretty sexual. Not my fav
# Text:
I’m playing on ps5 and it’s interesting.  It’s unique, massive, and has a neat story.  People are freaking out angry about this game.  I don’t think it’s a top 10 game but it’s definitely a good game on ps5 (played at launch).

In [7]:
idx = 10

title = df["title"][idx]
text = df["text"][idx]

print(f"# Title:\n{title}\n# Text:\n{text}")

# Title:
good
# Text:
good, a tad bit too bulky, but good. they stay on. good texture too.

In [9]:
idx = np.random.randint(0, len(df))

title = df["title"][idx]
text = df["text"][idx]

print(f"# Title:\n{title}\n# Text:\n{text}")

# Title:
Works perect and looks cool
# Text:
Way way cheaper than game stop and came in only a couple of days. It works awesome.  Added a rechargeable battery to it and I could not be happier.

In [10]:
idx = np.random.randint(0, len(df))

title = df["title"][idx]
text = df["text"][idx]

print(f"# Title:\n{title}\n# Text:\n{text}")

# Title:
Great if you're looking for a turn-based game
# Text:
The biggest draw for this game is the customization. The character customization had an almost overwhelming amount of options (a good thing!) and each class has a plethora of skills so you could easily have two characters of one class and play with them entirely different ways. The story is fun albeit predictable. I haven't played any of the older ones and I get the feeling I missed some in-jokes but nothing critical to the plot. The art is nice, as are the in game sprites.<br />The biggest issue with this game is that it doesn't really do anything groundbreaking in terms of the battle system or plot. They add in back-up turns and unison attacks, but otherwise it's just like every other turn-based game. If you're looking for change, this might not be for you.

### Missing values and quick stats

In [19]:
df.describe()

             rating                   timestamp  helpful_vote
count  4.624615e+06                     4624615  4.624615e+06
mean   4.047460e+00  2017-08-24 18:16:11.273000  1.227983e+00
min    1.000000e+00         1998-11-17 19:58:49 -1.000000e+00
25%    3.000000e+00         2015-03-06 10:19:18  0.000000e+00
50%    5.000000e+00  2018-03-14 22:52:57.208000  0.000000e+00
75%    5.000000e+00  2020-10-24 00:37:58.771000  1.000000e+00
max    5.000000e+00  2023-09-12 09:02:35.529000  1.036900e+04
std    1.430443e+00                         NaN  1.582127e+01

In [ ]:
# Boolean columns? No, apparently helpful_vote is not boolean. verified_purchase looks unary, might be better to drop it
df[["helpful_vote", "verified_purchase"]].mean()

helpful_vote         1.227983
verified_purchase    0.861219
dtype: float64

In [ ]:
# So helpful_vote is not boolean, is a count of votes. But still is kinda unary. Doesn't look very useful
df["helpful_vote"].value_counts(True) * 100

helpful_vote
0       74.749747
1       12.580096
2        4.340340
3        2.234175
4        1.325927
          ...
644      0.000022
2201     0.000022
542      0.000022
1164     0.000022
1013     0.000022
Name: proportion, Length: 810, dtype: float64

In [40]:
rev_drop_cols = ["images", "asin", "user_id", "helpful_vote", "helpful_vote", "verified_purchase"]

## Metadata dataset

In [11]:
df_meta = pd.read_json(meta_path, lines=True)
df_meta.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Video Games,Dash 8-300 Professional Add-On,5.0,1,[Features Dash 8-300 and 8-Q300 ('Q' rollout l...,[The Dash 8-300 Professional Add-On lets you p...,None,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aerosoft,"[Video Games, PC, Games]",{'Pricing': 'The strikethrough price is the Li...,B000FH0MHO,NaN,NaN,NaN
1,Video Games,Phantasmagoria: A Puzzle of Flesh,4.1,18,[Windows 95],[],None,[{'thumb': 'https://m.media-amazon.com/images/...,[],Sierra,"[Video Games, PC, Games]","{'Best Sellers Rank': {'Video Games': 137612, ...",B00069EVOG,NaN,NaN,NaN
2,Video Games,NBA 2K17 - Early Tip Off Edition - PlayStation 4,4.3,223,[The #1 rated NBA video game simulation series...,[Following the record-breaking launch of NBA 2...,58.0,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'NBA 2K17 - Kobe: Haters vs Players...,2K,"[Video Games, PlayStation 4, Games]","{'Release date': 'September 16, 2016', 'Best S...",B00Z9TLVK0,NaN,NaN,NaN
3,Video Games,Nintendo Selects: The Legend of Zelda Ocarina ...,4.9,22,[Authentic Nintendo Selects: The Legend of Zel...,[],37.42,[{'thumb': 'https://m.media-amazon.com/images/...,[],Amazon Renewed,"[Video Games, Legacy Systems, Nintendo Systems...","{'Best Sellers Rank': {'Video Games': 51019, '...",B07SZJZV88,NaN,NaN,NaN
4,Video Games,Thrustmaster Elite Fitness Pack for Nintendo Wii,3.0,3,"[Includes (9) Total Accessories, Pedometer, Wi...",[The Thrustmaster Motion Plus Elite Fitness Pa...,None,[{'thumb': 'https://m.media-amazon.com/images/...,[],THRUSTMASTER,"[Video Games, Legacy Systems, Nintendo Systems...","{'Release date': 'November 1, 2009', 'Pricing'...",B002WH4ZJG,NaN,NaN,NaN

In [15]:
df_meta.info()

<class 'pandas.DataFrame'>
RangeIndex: 137269 entries, 0 to 137268
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   main_category    126234 non-null  str
 1   title            137269 non-null  str
 2   average_rating   137269 non-null  float64
 3   rating_number    137269 non-null  int64
 4   features         137269 non-null  object
 5   description      137269 non-null  object
 6   price            62008 non-null   object
 7   images           137269 non-null  object
 8   videos           137269 non-null  object
 9   store            132908 non-null  str
 10  categories       137269 non-null  object
 11  details          137269 non-null  object
 12  parent_asin      137269 non-null  str
 13  bought_together  0 non-null       float64
 14  subtitle         350 non-null     str
 15  author           262 non-null     object
dtypes: float64(2), int64(1), object(8), str(5)
memory usage: 16.8+ MB

In [17]:
df_meta.isna().mean()

main_category      0.080390
title              0.000000
average_rating     0.000000
rating_number      0.000000
features           0.000000
description        0.000000
price              0.548274
images             0.000000
videos             0.000000
store              0.031770
categories         0.000000
details            0.000000
parent_asin        0.000000
bought_together    1.000000
subtitle           0.997450
author             0.998091
dtype: float64

In [ ]:
# I noticed that there're multiple main categories that are not precisely related to video games.
df_meta["main_category"].value_counts(True)

main_category
Video Games                     0.643686
Computers                       0.136532
All Electronics                 0.117369
Cell Phones & Accessories       0.030768
Toys & Games                    0.021650
Software                        0.011970
Industrial & Scientific         0.008548
Amazon Home                     0.005838
Home Audio & Theater            0.003509
Tools & Home Improvement        0.002923
Office Products                 0.002337
Sports & Outdoors               0.001933
Buy a Kindle                    0.001743
Movies & TV                     0.001561
Books                           0.001553
Musical Instruments             0.001220
All Beauty                      0.000998
Camera & Photo                  0.000927
Portable Audio & Accessories    0.000887
Digital Music                   0.000824
Health & Personal Care          0.000753
Automotive                      0.000673
AMAZON FASHION                  0.000428
Pet Supplies                    0.000301
Grocery                         0.000285
Baby                            0.000206
Arts, Crafts & Sewing           0.000174
Car Electronics                 0.000111
GPS & Navigation                0.000103
Appliances                      0.000087
Amazon Devices                  0.000032
Audible Audiobooks              0.000024
Collectible Coins               0.000024
Gift Cards                      0.000008
Handmade                        0.000008
                                0.000008
Name: proportion, dtype: float64

After noticing that there're multiple categories that are not Video Games, I wanted to explore some cases manually.

In [ ]:
# All Beauty - This case is not a videogame but in a way it's related to video games (I also don't think this should be catalogued as all beauty).
idx = 3592

title = df_meta["title"][idx]
description = df_meta["description"][idx]
parent_asin = df_meta["parent_asin"][idx]
details = df_meta["details"][idx]
cats = df_meta["categories"][idx]
image_links = df_meta["images"][idx]

print(f"# Title:\n{title}\n# Description:\n{description}\n# Parent ASIN:\n{parent_asin}\n# Details:\n{details}\n# Categories:\n{cats}\n# Image Links:\n{image_links}")

# Title:
Hello Kitty Glitter DSL/DSi Girls Game Case PINK
# Description:
['For the glitter-loving gamer, this Hello Kitty game case is the purr-fect accessory. PVC Wipe clean Imported Girls game case from Hello Kitty Glitter material; Hello Kitty graphic Detachable wristband with metal hardware Organizational features inside WARNING: Choking HAZARD not for children under 3 years']
# Parent ASIN:
B00FI7KB2C
# Details:
{'Brand': 'Hello Kitty', 'Color': 'Pink', 'Material': 'Polyvinyl Chloride (PVC)', 'Closure Type': 'Zipper', 'Pattern': 'Cartoon', 'Is Discontinued By Manufacturer': 'No', 'Package Dimensions': '6.5 x 4.3 x 1.9 inches; 4.16 Ounces', 'UPC': '688955827097'}
# Categories:
['Video Games', 'Legacy Systems', 'Nintendo Systems', 'Nintendo DS', 'Accessories', 'Cases & Storage']
# Image Links:
[{'thumb': 'https://m.media-amazon.com/images/I/51XXHGzR3kL._SS40_.jpg', 'large': 'https://m.media-amazon.com/images/I/51XXHGzR3kL.jpg', 'variant': 'MAIN', 'hi_res': None}, {'thumb': 'https://m.media-amazon.com/images/I/51XXHGzR3kL._SS40_.jpg', 'large': 'https://m.media-amazon.com/images/I/51XXHGzR3kL.jpg', 'variant': 'PT01', 'hi_res': None}]

In [27]:
df[df["parent_asin"] == "B00FI7KB2C"]["text"][2256369]

'Nice quality and the color shown was the color that arrived. Loved the glitter/shimmer look very girly and cute.'

In [ ]:
# Buy a Kindle - These Buy a Kindle cases are definitely not related to video games.
idx = 2180

title = df_meta["title"][idx]
description = df_meta["description"][idx]
parent_asin = df_meta["parent_asin"][idx]
details = df_meta["details"][idx]
cats = df_meta["categories"][idx]
image_links = df_meta["images"][idx]

print(f"# Title:\n{title}\n# Description:\n{description}\n# Parent ASIN:\n{parent_asin}\n# Details:\n{details}\n# Categories:\n{cats}\n# Image Links:\n{image_links}")

# Title:
The Mine: Tales From a Revolution - Connecticut
# Description:
[]
# Parent ASIN:
B082FY6DFZ
# Details:
{'Publisher': 'Brief Candle Press (March 18, 2020)', 'Publication date': 'March 18, 2020', 'Language': 'English', 'File size': '2482 KB', 'Simultaneous device usage': 'Unlimited', 'Text to Speech': 'Enabled', 'Screen Reader': 'Supported', 'Enhanced typesetting': 'Enabled', 'X Ray': 'Not Enabled', 'Word Wise': 'Enabled', 'Sticky notes': 'On Kindle Scribe', 'Print length': '208 pages', 'Page numbers source ISBN': '1942319371'}
# Categories:
['Video Games', 'PC', 'Games']
# Image Links:
[{'large': 'https://m.media-amazon.com/images/I/514LkxNNOkL.jpg', 'variant': 'MAIN'}]

In [ ]:
# Buy a Kindle - Yup, same conclusion here.
idx = 136490

title = df_meta["title"][idx]
description = df_meta["description"][idx]
parent_asin = df_meta["parent_asin"][idx]
details = df_meta["details"][idx]
cats = df_meta["categories"][idx]
image_links = df_meta["images"][idx]

print(f"# Title:\n{title}\n# Description:\n{description}\n# Parent ASIN:\n{parent_asin}\n# Details:\n{details}\n# Categories:\n{cats}\n# Image Links:\n{image_links}")

# Title:
The Flea: The Amazing Story of Leo Messi (Football Stars Series)
# Description:
['Review', 'This is a great story and well written in a style that makes it a fun and an easy read while providing all the background and insight into this amazing super star! Kids and adults alike will find this a rewarding read. -- Francis J. Fabian Jr. "Amazon.com"', '--This text refers to the', 'paperback', 'edition.', 'About the Author', "Michael Part is a soccer fan, a screenwriter and author. Michael wrote the critically acclaimed The Flea - The Amazing Story of Leo Messi, Cristiano Ronaldo - The Rise of a Winner, Neymar The Wizard, The Pope Who Loves Soccer, and his much anticipated new book, Balotelli The Untold Story to be published by Sole Books in September, 2015. \xa0He also wrote the Disney classic movie, A Kid in King Arthur's Court. Michael is also the editor of a number of young adult books as well as the American editor of the bestselling children's series of books, The Wild Soccer Bunch.", '--This text refers to the', 'paperback', 'edition.']
# Parent ASIN:
B075V5Z9HX
# Details:
{'Publisher': 'Sole Books (September 21, 2017)', 'Publication date': 'September 21, 2017', 'Language': 'English', 'File size': '988 KB', 'Text to Speech': 'Enabled', 'Screen Reader': 'Supported', 'Enhanced typesetting': 'Enabled', 'X Ray': 'Not Enabled', 'Word Wise': 'Enabled', 'Sticky notes': 'On Kindle Scribe', 'Print length': '144 pages', 'Page numbers source ISBN': '1938591534'}
# Categories:
['Video Games', 'Legacy Systems', 'Nintendo Systems']
# Image Links:
[]

In [ ]:
meta_drop_cols = ["bought_together", "subtitle", "author", "images", "videos"]

## Merge

In [41]:
df = df.drop(columns = rev_drop_cols)
df.head(2)

,rating,title,text,parent_asin,timestamp
0,4,It’s pretty sexual. Not my fav,I’m playing on ps5 and it’s interesting. It’s...,B07DK1H3H5,2020-12-17 06:33:24.795
1,5,Good. A bit slow,Nostalgic fun. A bit slow. I hope they don’t...,B07SRWRH5D,2020-04-16 15:31:54.941

In [42]:
df_meta = df_meta.drop(columns = meta_drop_cols)
df_meta.head(2)

,main_category,title,average_rating,rating_number,features,description,price,store,categories,details,parent_asin
0,Video Games,Dash 8-300 Professional Add-On,5.0,1,[Features Dash 8-300 and 8-Q300 ('Q' rollout l...,[The Dash 8-300 Professional Add-On lets you p...,None,Aerosoft,"[Video Games, PC, Games]",{'Pricing': 'The strikethrough price is the Li...,B000FH0MHO
1,Video Games,Phantasmagoria: A Puzzle of Flesh,4.1,18,[Windows 95],[],None,Sierra,"[Video Games, PC, Games]","{'Best Sellers Rank': {'Video Games': 137612, ...",B00069EVOG

In [43]:
print(f"# rows in reviews: {len(df)} \n# rows in metadata: {len(df_meta)}")

# rows in reviews: 4624615
# rows in metadata: 137269

In [46]:
df_meta["parent_asin"].value_counts()[:10]

parent_asin
B000FH0MHO    1
B00069EVOG    1
B00Z9TLVK0    1
B07SZJZV88    1
B002WH4ZJG    1
B00005Y3OJ    1
B0001ZNU56    1
B07H93H878    1
B009C9E8JY    1
B00006969T    1
Name: count, dtype: int64

In [47]:
df["parent_asin"].value_counts()[:10]

parent_asin
B01N3ASPNV    18105
B0BN942894    17310
B077GG9D5D    15594
B000N5Z2L4    13329
B0086VPUHI    12100
B004RMK5QG    10256
B07YBXFDYN     9430
B00BGA9WK2     8089
B07V8YSBFG     7844
B07CRX5X9T     7570
Name: count, dtype: int64

In [50]:
df["parent_asin"].nunique()

137249

In [48]:
df_all = df_meta.merge(df, on = "parent_asin", how = "left")
df_all.head(2)

,main_category,title_x,average_rating,rating_number,features,description,price,store,categories,details,parent_asin,rating,title_y,text,timestamp
0,Video Games,Dash 8-300 Professional Add-On,5.0,1,[Features Dash 8-300 and 8-Q300 ('Q' rollout l...,[The Dash 8-300 Professional Add-On lets you p...,None,Aerosoft,"[Video Games, PC, Games]",{'Pricing': 'The strikethrough price is the Li...,B000FH0MHO,5.0,Dash 8-300,I bought the Dash 8-300 FS2002/2004 several ye...,2012-05-26 11:03:49
1,Video Games,Phantasmagoria: A Puzzle of Flesh,4.1,18,[Windows 95],[],None,Sierra,"[Video Games, PC, Games]","{'Best Sellers Rank': {'Video Games': 137612, ...",B00069EVOG,5.0,Brings back memories,my fiance played this game a long time ago and...,2014-04-29 15:03:25

In [49]:
df_all.shape

(4624635, 15)

## Conclusions

We decided to drop the following columns:
- **reviews**
    - images: We won't be retrieving or analyzing images in our project. That would be out of the scope, so we can drop it.
    - asin: This ID is not useful to do any joins (we use `parent_asin` to do the join with metadata). Since it has no use, we can drop it. The tradeoff could be that the agent won't be able to give answers at asin level.
    - user_id: We have no use case for this column. Queries on users will be not possible, but the loss of this case doesn't hurt.
    - helpful_vote: This column is unary, so it doesn't really bring a lot of value.
    - verified_purchase: This column is also unary, therefore it doesn't really bring a lot of value.
    
- **metadata**
    - main_category: This column is redundant. We already know that the category is Video Games.
    - bought_together: This column is completely or almost completely null, so we decided to drop it.
    - subtitle: This column is completely or almost completely null, so we decided to drop it.
    - author: This column is completely or almost completely null, so we decided to drop it.
    - images: We won't be retrieving or analyzing images in our project, nor their urls. That would be out of the scope, so we can drop it.
    - videos: We won't be retrieving or analyzing videos in our project, nor their urls. That would be out of the scope, so we can drop it.

Then, we also noticed that the `main_category` in the metadata dataset is not always video games and that many cases are not very video games related, like the examples we found of _"Buy a Kindle"_.